# Conda environment
name: template_builder
channels:
  - default
  - cta-observatory
dependencies:
  - astropy
  - ctapipe
  - ipython
  - jupyter
  - matplotlib
  - numpy>=1.15.4
  - pytest
  - pytest-cov
  - pytest-runner
  - pyyaml
  - scikit-learn
  - scipy
  - setuptools
  - sphinx
  - sphinx_rtd_theme
  - tqdm
  - pip
  - pip:
    - git+https://github.com/ParsonsRD/submit_SGE.git
    - loess
