
ShowerSimulation:

  event_number: 200
  zenith_scaling: True
  min_events: 1
  scaling_index: -1.5

  altitude:
        - 90
  azimuth:
        - 166 # Subtract the 14 deg B field rotation

  energy_bins:
        - 7.94328235e-02
        - 1.25892541e-01
        - 1.99526231e-01
        - 3.16227766e-01
        - 5.01187234e-01
        - 7.94328235e-01
        - 1.25892541e+00
        - 1.99526231e+00
        - 3.16227766e+00
        - 5.01187234e+00
        - 7.94328235e+00
        - 1.25892541e+01
        - 1.99526231e+01
        - 3.16227766e+01
        - 5.01187234e+01
        - 7.94328235e+01
        - 1.25892541e+02
        - 1.99526231e+02
        - 3.16227766e+02

  core_bins:
            - 0
            - 25
            - 50
            - 75
            - 100
            - 125
            - 150
            - 175
            - 200
            - 250
            - 300
            - 350
            - 400
            - 450
            - 500
            - 600
            - 700
            - 800
            - 900
            - 1000

  rotation_angle:
            - 0

  diameter: 15

TelescopeSimulation:

  config_name: "HESS1_preupgrade"
  config_file: "hess-phase2b.cfg"
  atmosphere: "atm_trans_1835_1_10_0_0_1835.dat"
  sim_telarray_directory: "/Users/dparsons/Unix/Software/SimTelArray/std"
  extra_options: " -DCT1" # with HESS sims we need to specify telescope
  optical_efficiency: 0.7