
ShowerSimulation:

  event_number: 1000
  zenith_scaling: True
  min_events: 200
  scaling_index: -1.5

  altitude:
        - 70
  azimuth:
        - 0
        - 180

  energy_bins:
        - 3.16227766e-01
        - 5.01187234e-01
        - 7.94328235e-01
        - 1.25892541e+00
        - 1.99526231e+00
        - 3.16227766e+00
        - 5.01187234e+00
        - 7.94328235e+00
        - 1.25892541e+01
        - 1.99526231e+01
        - 3.16227766e+01
        - 5.01187234e+01
        - 7.94328235e+01
        - 1.25892541e+02
        - 1.99526231e+02
        - 3.16227766e+02

  core_bins:
            - 0
            - 25
            - 50
            - 75
            - 100
            - 125
            - 150
            - 175
            - 200
            - 250
            - 300
            - 350
            - 400
            - 450
            - 500
            - 600
            - 700
            - 800
            - 900
            - 1000

  rotation_angle:
            - 0
  diameter: 5

TelescopeSimulation:

  config_name: "GCT"
  config_file: "cfg/CTA/CTA-ULTRA6-SST-GCT.cfg"
  atmosphere: "atm_trans_2150_1_10_0_0_2150.dat"
  sim_telarray_directory: "/Users/dparsons/Unix/Software/SimTelArray/std"
  extra_options: ""
  optical_efficiency: 1