CORSIKA:

  ESLOPE: -2.0
  VIEWCONE: 0.0 0.5

  OBSLEV: 2150.E2
  ATMOSPHERE: 26 Y
  MAGNET: 21.325 -8.926

  CSCAT:  1  0.  0.

  TSTART:  T
  ECUTS:   0.3  0.1  0.020  0.020
  MUADDI:  F
  MUMULT:  T
  LONGI:   T  1.  F  F
  MAXPRT:  0
  ECTMAP:  1.E6
  STEPFC:  1.0

  CERSIZ:  5.
  CERFIL:  F
  CWAVLG:  240.  700.

  DEBUG:   F  6  F  1000000
  DIRECT:  /dev/null

  IACT SPLIT_AUTO: 15M
  IACT IO_BUFFER: 4000MB
  IACT MAX_BUNCHES: 10000000
